// Generated by CoffeeScript 1.3.0
(function() {
  var colors, exec, getBranch, getPass, getRunner, getUser, getWebhook, git, gitContinue, readStdout, readyCallback;

  exec = require('child_process').exec;

  colors = require('colors');

  readyCallback = null;

  git = module.exports = {
    runner: '',
    branch: '',
    user: '',
    pass: '',
    config: {
      runner: 'concrete.runner',
      branch: 'concrete.branch',
      user: 'concrete.user',
      pass: 'concrete.pass',
      webhook: 'concrete.webhook'
    },
    init: function(target, callback) {
      var fs, path;
      readyCallback = callback;
      path = require('path');
      fs = require('fs');
      if (target.toString().charAt(0) !== '/') {
        target = process.cwd() + '/' + target;
      }
      process.chdir(target);
      git.target = path.normalize(target + '/.git/');
      git.failure = path.normalize(target + '/.git/hooks/build-failed');
      git.success = path.normalize(target + '/.git/hooks/build-worked');
      return fs.exists(git.target, function(exists) {
        if (exists === false) {
          console.log(("'" + target + "' is not a valid Git repo").red);
          process.exit(1);
        }
        getUser();
        getPass();
        getWebhook();
        getBranch();
        return getRunner();
      });
    },
    pull: function(next) {
      var jobs, out;
      jobs = require('./jobs');
      out = "Pulling '" + git.branch + "' branch";
      return jobs.updateLog(jobs.current, out, function() {
        var _this = this;
        console.log(out.grey);
        return exec('git fetch && git reset --hard origin/' + git.branch, function(error, stdout, stderr) {
          if (error != null) {
            out = "" + error;
            jobs.updateLog(jobs.current, out);
            return console.log(out.red);
          } else {
            out = "Updated '" + git.branch + "' branch";
            return jobs.updateLog(jobs.current, out, function() {
              console.log(out.grey);
              return next();
            });
          }
        });
      });
    },
    lastCommit: function(callback) {
      var _this = this;
      return exec("git fetch && git rev-list --pretty=format:'%h::::%s::::%ad' -n1 origin/" + git.branch, function(err, stdo, stderr) {
        var commit, p;
        commit = stdo.split(/(\n|\r)+/);
        p = commit[2].split('::::');
        commit = {
          sha: p[0],
          message: p[1],
          time: new Date(Date.parse(p[2]))
        };
        return callback(commit);
      });
    },
    addNote: function(sha, message) {
      var _this = this;
      return exec("git notes --ref=ci add -f -m \"" + message + "\" " + sha, function(err, stdo, stderr) {});
    }
  };

  readStdout = function(stdout) {
    return stdout.toString().replace(/[\s\r\n]+$/, '');
  };

  getUser = function() {
    var _this = this;
    return exec('git config --get ' + git.config.user, function(error, stdout, stderr) {
      if (error != null) {
        return git.user = '';
      } else {
        return git.user = readStdout(stdout);
      }
    });
  };

  getPass = function() {
    var _this = this;
    return exec('git config --get ' + git.config.pass, function(error, stdout, stderr) {
      if (error != null) {
        return git.pass = '';
      } else {
        return git.pass = readStdout(stdout);
      }
    });
  };

  getWebhook = function() {
    var _this = this;
    return exec('git config --get ' + git.config.webhook, function(error, stdout, stderr) {
      if (error != null) {
        return git.webhook = '/webhook';
      } else {
        return git.webhook = readStdout(stdout);
      }
    });
  };

  getBranch = function() {
    var _this = this;
    return exec('git config --get ' + git.config.branch, function(error, stdout, stderr) {
      if (error != null) {
        git.branch = 'master';
        return gitContinue();
      } else {
        git.branch = readStdout(stdout);
        if (git.branch === '') {
          git.branch = 'master';
        }
        return gitContinue();
      }
    });
  };

  getRunner = function() {
    var _this = this;
    return exec('git config --get ' + git.config.runner, function(error, stdout, stderr) {
      if (error != null) {
        console.log(("Git.getRunner: " + error).red);
        return process.exit(1);
      } else {
        git.runner = readStdout(stdout);
        if (git.runner === '') {
          git.runner = 'none';
        }
        return gitContinue();
      }
    });
  };

  gitContinue = function() {
    if (git.branch === 'none') {
      git.branch = 'master';
    } else if (git.branch === '') {
      return false;
    }
    if (git.runner === 'none') {
      console.log('Git.gitContinue: You must specify a Git runner'.red);
      process.exit(1);
    } else if (git.runner === '') {
      return false;
    }
    return readyCallback();
  };

}).call(this);
