// Generated by CoffeeScript 1.3.0
(function() {
  var app, auth, express, fs, git, jobs, moment, path, runner, stats, stylus;

  express = require('express');

  stylus = require('stylus');

  fs = require('fs');

  path = require('path');

  runner = require('./runner');

  jobs = require('./jobs');

  git = require('./git');

  moment = require('moment');

  stats = require('./stats');

  app = module.exports = express();

  if (git.user && git.pass) {
    auth = express.basicAuth(function(user, pass) {
      return user === git.user && pass === git.pass;
    });
  } else {
    auth = function() {
      return true;
    };
  }

  app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('quiet', true);
    app.set('view engine', 'coffee');
    app.engine('coffee', require('coffeecup').__express);
    app.set('view options', {
      layout: false
    });
    app.use(stylus.middleware({
      debug: false,
      src: __dirname + '/views',
      dest: __dirname + '/public',
      compile: function(str) {
        return stylus(str).set('compress', true);
      }
    }));
    app.use(express.logger());
    app.use(app.router);
    return app.use(express["static"](__dirname + '/public'));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.get('/', function(req, res) {
    return jobs.getLatest(function(jobs) {
      return res.render('index', {
        project: path.basename(process.cwd()),
        jobs: jobs,
        moment: moment
      });
    });
  });

  app.get('/stats', function(req, res) {
    return res.render('stats', {
      project: path.basename(process.cwd())
    });
  });

  app.get('/jobs', auth, function(req, res) {
    return jobs.getAll(function(jobs) {
      return res.json(jobs);
    });
  });

  app.get('/job/:id', auth, function(req, res) {
    return jobs.get(req.params.id, function(job) {
      return res.json(job);
    });
  });

  app.get('/job/:id/:attribute', auth, function(req, res) {
    return jobs.get(req.params.id, function(job) {
      if (job[req.params.attribute] != null) {
        return res.json(job[req.params.attribute]);
      } else {
        return res.send("The job doesn't have the " + req.params.attribute + " attribute");
      }
    });
  });

  app.get('/clear', auth, function(req, res) {
    return jobs.clear(function() {
      return res.redirect('/jobs');
    });
  });

  app.get('/add', auth, function(req, res) {
    return jobs.addJob(function() {
      return res.redirect('/jobs');
    });
  });

  app.get('/ping', auth, function(req, res) {
    return jobs.getLast(function(job) {
      if (job.failed) {
        return res.send(412);
      } else {
        return res.send(200);
      }
    });
  });

  app.post('/', auth, function(req, res) {
    return jobs.addJob(function(job) {
      runner.build();
      if (req.xhr) {
        console.log(job);
        return res.json(job);
      } else {
        return res.redirect('/');
      }
    });
  });

  app.get('/stats/build-time', auth, function(req, res) {
    return stats.buildTime(function(builds) {
      return res.json(builds);
    });
  });

  app.get('/stats/number-of-tests', auth, function(req, res) {
    return stats.numberOfTests(function(n) {
      return res.json(n);
    });
  });

  app.post(git.webhook, function(req, res) {
    console.log("GitHub webhook received.");
    return jobs.addJob(function(job) {
      runner.build();
      return res.send(200);
    });
  });

}).call(this);
